### ISSUE TITLE
Icon documentation

### ISSUE THREAD

**Issue by eddsalkield** [iSparsh/gross#1]
Hi there!  Firstly, thanks so much for releasing this - it's a really neat setup.

I'm having some troubles however, because I don't know where to obtain the icon sets from.  Would you be able to document this in the repo?  Thanks!

**Comment by iSparsh** [comment]
Hi there, sorry for the extremely late response. The icons are just Nerd Fonts that you can take a look at [here](https://www.nerdfonts.com/)
