### ISSUE TITLE
not an issue, just a question

### ISSUE THREAD

**Issue by iguesspaul** [iSparsh/gross#2]
Hey, I've recently started working with eww to make my desktop look nicer when I stumbled across this. I use it a lot for reference, and I have a question. How did you make it drop down? 

I'm thinking about making a similar thing, but with it popping up from the side. I saw that you said you used it in combination with polybar, which is perfect since that is what I use for my bar too. 

Thanks!

**Comment by iSparsh** [comment]
Sorry for the extremely late response. I am not on my machine so I can't exactly share the code with you, but refer to [this](https://github.com/polybar/polybar/issues/276) to make a button out of a text box in polybar. And in the command, I just have `eww open ...` for the window to open.
